apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: relayer-smart-contract
version: 0.1.1
icon: https://theme.zdassets.com/theme_assets/2204032/2f5b4e1585e18810c3a9435e1ec3cf41836a5e57.svg
